function includesAny(text, words) {
  text = text || ''
  for (var i = 0; i < words.length; i++) {
    if (text.indexOf(words[i]) >= 0) return true
  }
  return false
}

function detectTheme(result) {
  var text = [result.category || '', result.testTitle || '', result.resultTitle || ''].join('')
  if (includesAny(text, ['消费', '购物', '预算', '花钱', '下单', '价格', '性价比'])) {
    return { key: 'consume', name: '消费风格报告', icon: '🛍️', gradientClass: 'theme-consume' }
  }
  if (includesAny(text, ['干饭', '奶茶', '食堂', '饮食', '零食'])) {
    return { key: 'food', name: '干饭能量报告', icon: '🧋', gradientClass: 'theme-food' }
  }
  if (includesAny(text, ['朋友', '搭子', '群聊', '社交', '同桌'])) {
    return { key: 'social', name: '好友关系报告', icon: '🤝', gradientClass: 'theme-social' }
  }
  if (includesAny(text, ['摆烂', '回血', '电量', '拖延', '犯困'])) {
    return { key: 'recharge', name: '今日电量报告', icon: '🔋', gradientClass: 'theme-recharge' }
  }
  if (includesAny(text, ['人设', '显眼包', '班级', '宿舍', '性格', '摸鱼', '观察者', '实力派'])) {
    return { key: 'persona', name: '校园人格报告', icon: '🎭', gradientClass: 'theme-persona' }
  }
  if (includesAny(text, ['今日', '状态', '校园'])) {
    return { key: 'daily', name: '今日状态报告', icon: '✨', gradientClass: 'theme-daily' }
  }
  return { key: 'general', name: '趣测星球报告', icon: '🌟', gradientClass: 'theme-general' }
}

function card(icon, title, text) {
  return { icon: icon, title: title, text: text }
}

function action(icon, text) {
  return { icon: icon, text: text }
}

function bar(label, value, tone) {
  return { label: label, value: value, tone: tone }
}

/**
 * A per-result profile map. Keys are the exact result titles generated by seedTests/submitTest.
 * This keeps the visual report matched to the test outcome instead of using one generic block per category.
 */
function getProfile(resultTitle) {
  var profiles = {
    '佛系待机中': {
      tags: ['佛系待机', '低压模式', '慢慢来', '舒适优先'],
      lead: '你的答案更偏向低压、慢热、先观察再行动。',
      cards: [card('☁️', '状态主线', '今天的你不太想被催促，适合把任务降到最小颗粒度，一点点进入状态。'), card('🍃', '选择线索', '你在题目里更倾向安全、舒服、少消耗的选项，说明当前需要的是恢复感。'), card('🧭', '使用说明', '不要硬装满格在线，先完成一个最轻的小动作，状态会自然回温。')],
      bars: [bar('松弛度', 88, 'purple'), bar('行动启动', 42, 'blue'), bar('回血空间', 76, 'pink')],
      actions: [action('🍵', '先给自己 10 分钟缓冲，不急着进入高强度模式。'), action('✅', '只挑一件最容易完成的小事，把“开始”做出来。'), action('🌙', '今天少和别人比效率，保住自己的节奏更重要。')],
      share: '我今天是佛系待机中，主打一个慢慢回血。'
    },
    '半上线半摸鱼': {
      tags: ['半上线', '摸鱼雷达', '弹性节奏', '能做但不多做'],
      lead: '你的答案显示：你不是没状态，而是只想把电用在值得的地方。',
      cards: [card('🎒', '状态主线', '你能完成必要任务，但对额外消耗比较敏感，适合“该做做，该摸摸”的弹性节奏。'), card('🐟', '选择线索', '你的选择在负责和放空之间来回切换，说明你正在给自己找一个舒服的平衡点。'), card('⏱️', '使用说明', '把任务拆成上课版、课间版、放学版，别要求自己一直在线。')],
      bars: [bar('在线感', 62, 'blue'), bar('摸鱼欲', 84, 'purple'), bar('任务完成率', 58, 'pink')],
      actions: [action('📌', '把今天必须做的事压缩成 1 个重点。'), action('🐟', '允许自己摸鱼，但给摸鱼设置一个结束点。'), action('🍬', '完成重点后再奖励自己一段无负担放空。')],
      share: '我今天半上线半摸鱼，精准分配每一格电量。'
    },
    '满格在线中': {
      tags: ['满格在线', '课堂活跃', '推进力', '元气输出'],
      lead: '你的答案明显偏向积极参与和主动推进，今天适合把重要事情往前推。',
      cards: [card('⚡', '状态主线', '你今天的反应速度和参与感都比较高，适合处理需要表达、沟通、执行的事情。'), card('🌈', '选择线索', '你在多个场景里都选择了更主动的处理方式，说明能量正在可用区间。'), card('🧯', '使用说明', '状态好也别一次性耗尽，给自己留一点余电，明天才不会断崖式掉线。')],
      bars: [bar('在线感', 90, 'pink'), bar('行动力', 86, 'blue'), bar('续航保护', 68, 'purple')],
      actions: [action('🚀', '趁状态好先推进最重要的一件事。'), action('💬', '适合主动沟通，今天说出口的效率会更高。'), action('🧃', '忙完记得补水休息，别把满格用成透支。')],
      share: '我今天满格在线中，适合把重要任务一口气推进。'
    },
    '超频运行中': {
      tags: ['超频运行', '高能模式', '想法很多', '注意降温'],
      lead: '你的选择像开启了高性能模式，什么都想参与，但也容易过热。',
      cards: [card('🔥', '状态主线', '你今天的兴奋度和参与欲都很高，容易同时开启多个任务线。'), card('🎢', '选择线索', '你偏向快节奏、高刺激、高参与的选项，说明当下能量很冲。'), card('🧊', '使用说明', '超频不是坏事，但要给自己设置冷却时间，避免晚上突然没电。')],
      bars: [bar('爆发力', 96, 'pink'), bar('分心风险', 78, 'purple'), bar('节奏控制', 52, 'blue')],
      actions: [action('🎯', '只选 2 件最值得冲的事，别全都接。'), action('⏳', '每 40 分钟强制停一下，给大脑降温。'), action('🧊', '睡前减少刺激内容，避免能量刹不住。')],
      share: '我今天超频运行中，能量很满但需要降温。'
    },
    '班级显眼包': {
      tags: ['显眼包', '气氛发动机', '活跃担当', '有梗体质'],
      lead: '你的人格结果不是泛泛的“外向”，而是典型的校园气氛发动机。',
      cards: [card('🎤', '人格高光', '你在班级里很容易把气氛带起来，活跃、接梗、制造笑点是你的天然技能。'), card('📣', '选择线索', '你的选择多次偏向主动表达和带节奏，说明你不怕被看见，也愿意让场子热起来。'), card('🪫', '反差提醒', '显眼包也会累，偶尔安静不营业，不代表你不有趣。')],
      bars: [bar('活跃度', 94, 'pink'), bar('控场感', 82, 'purple'), bar('安静充电', 46, 'blue')],
      actions: [action('🎭', '今天可以继续活跃气氛，但别强迫自己每秒都有梗。'), action('💬', '把一个好笑瞬间发给朋友，快乐会加倍。'), action('🔋', '给自己留一段不营业时间，显眼包也需要回血。')],
      share: '我的校园隐藏人设是班级显眼包，走到哪都自带气氛。'
    },
    '专业摸鱼选手': {
      tags: ['摸鱼王', '表面认真', '节能高手', '松弛感'],
      lead: '你的人格核心不是懒，而是很会判断什么时候该省电。',
      cards: [card('🐟', '人格高光', '你看起来云淡风轻，其实很懂校园生存节奏：该过就过，该躲就躲。'), card('🕶️', '选择线索', '你在题目里多次选择低消耗路径，说明你擅长用最少能量维持基本盘。'), card('🎯', '进阶提醒', '摸鱼智慧用对地方就是效率；关键节点别错过，你会更稳。')],
      bars: [bar('节能能力', 92, 'purple'), bar('课堂伪装', 84, 'blue'), bar('关键爆发', 56, 'pink')],
      actions: [action('📌', '把今天必须完成的事标出来，别让摸鱼误伤重点。'), action('🐟', '给自己安排合法摸鱼时间，摸得更安心。'), action('⚡', '关键任务只冲 15 分钟，先把开头做掉。')],
      share: '我的校园隐藏人设是专业摸鱼选手，节能但不掉线。'
    },
    '低调实力派': {
      tags: ['低调实力派', '靠谱认真', '稳定输出', '隐藏学霸'],
      lead: '你的人格结果更接近稳定型输出者：不吵，但关键时刻很能顶。',
      cards: [card('📚', '人格高光', '你可能不是最爱表现的人，但作业、笔记、任务质量往往能让人放心。'), card('🧩', '选择线索', '你的选择偏向认真、承担和把事情做好，说明你在意质量胜过热闹。'), card('✨', '反差空间', '低调不是隐身，该展示成果的时候可以更大方一点。')],
      bars: [bar('可靠度', 95, 'blue'), bar('专注力', 86, 'purple'), bar('展示欲', 48, 'pink')],
      actions: [action('📖', '把一个你做得不错的成果大方展示出来。'), action('✅', '今天适合推进需要耐心和质量的任务。'), action('🌟', '别只做幕后高手，适当让别人看见你的实力。')],
      share: '我的校园隐藏人设是低调实力派，不吵但很能打。'
    },
    '隐藏观察者': {
      tags: ['隐藏观察者', '安静雷达', '细节捕手', '慢热型'],
      lead: '你的人格不是没有存在感，而是更擅长安静观察和精准感知。',
      cards: [card('👀', '人格高光', '你安静但不迟钝，很多班级里的细节、人际变化和情绪信号你都看得很清楚。'), card('🌙', '选择线索', '你的答案多次偏向先观察、少打扰、等合适时机再行动，说明你是慢热但细腻的类型。'), card('💬', '反差空间', '当你愿意开口时，别人会发现你其实一直都有想法，而且很准。')],
      bars: [bar('观察力', 94, 'purple'), bar('表达外放', 40, 'blue'), bar('共情细节', 82, 'pink')],
      actions: [action('📝', '把今天观察到的一件有趣小事记录下来。'), action('💬', '尝试主动说出一个观点，不用很长，一句就够。'), action('🤝', '找一个熟悉的人轻松聊两句，慢热也可以被看见。')],
      share: '我的校园隐藏人设是隐藏观察者，安静但什么都看在眼里。'
    },
    '奶茶续命型选手': {
      tags: ['奶茶续命', '甜度补给', '快乐开关', '新品雷达'],
      lead: '你的饮食人格很明确：情绪回血和快乐补给常常从一杯奶茶开始。',
      cards: [card('🧋', '补给偏好', '你把奶茶当成校园生活的仪式感，一杯下去，课也没那么难熬了。'), card('🍯', '选择线索', '你的选择偏向饮料、新品、甜味和即时快乐，说明你需要可见的情绪奖励。'), card('💧', '平衡建议', '奶茶很快乐，但别让它承担全部回血任务，偶尔也给身体一点清爽补给。')],
      bars: [bar('甜度依赖', 91, 'pink'), bar('新品敏感', 84, 'purple'), bar('正餐稳定', 52, 'blue')],
      actions: [action('🧋', '今天可以喝，但选一个真正想喝的，不为凑单硬买。'), action('💧', '顺手补一杯水，快乐和健康都要有。'), action('📸', '把今日奶茶当成小确幸记录下来。')],
      share: '我的干饭奶茶人格是奶茶续命型选手，快乐开关在杯子里。'
    },
    '食堂干饭王': {
      tags: ['干饭王', '食堂地图', '窗口情报', '热饭治愈'],
      lead: '你的饮食人格偏向实打实的热量补给：吃饱，世界就稳了。',
      cards: [card('🍚', '补给偏好', '你对食堂窗口和饭点节奏有自己的判断，下课铃一响就是行动信号。'), card('🥢', '选择线索', '你的答案更偏向正餐、热饭和明确满足感，说明你相信“吃饱才有力气”。'), card('🌿', '平衡建议', '干饭是生活热情，也可以偶尔搭配蔬菜水果，让续航更稳。')],
      bars: [bar('干饭速度', 93, 'pink'), bar('窗口熟悉度', 88, 'blue'), bar('营养平衡', 62, 'purple')],
      actions: [action('🍱', '今天认真吃一顿正餐，别用零食糊弄。'), action('🤝', '约一个饭搭子，快乐干饭加倍。'), action('🥬', '顺手加一个清爽菜，干饭王也要长期续航。')],
      share: '我的干饭奶茶人格是食堂干饭王，下课铃就是冲锋号。'
    },
    '课桌零食库管理员': {
      tags: ['零食库', '抽屉补给站', '分享型快乐', '随时回血'],
      lead: '你的饮食人格是移动小卖部型：快乐要随手可得，也愿意分给别人。',
      cards: [card('🍪', '补给偏好', '你的课桌像一个安全补给点，饿了、困了、烦了，都能摸出点东西回血。'), card('🎁', '选择线索', '你多次选择囤货和即时零食，说明你很重视可掌控的小快乐。'), card('🍎', '平衡建议', '零食库可以继续营业，但建议混入一点更耐吃、更健康的存货。')],
      bars: [bar('囤货能力', 94, 'purple'), bar('分享欲', 78, 'pink'), bar('正餐提醒', 50, 'blue')],
      actions: [action('🍫', '整理一下抽屉，把快过期的零食先解决。'), action('🍎', '下次囤货加一点坚果/水果干。'), action('🤲', '分一点给朋友，零食快乐会变成社交快乐。')],
      share: '我的干饭奶茶人格是课桌零食库管理员，抽屉就是补给站。'
    },
    '佛系饮食派': {
      tags: ['佛系饮食', '随缘吃啥', '不纠结', '淡定派'],
      lead: '你的饮食人格是随缘型：不太为吃什么内耗，能吃饱就很稳。',
      cards: [card('🍃', '补给偏好', '别人纠结吃什么时，你通常能很快接受一个方案，省下大量选择成本。'), card('🧘', '选择线索', '你的答案偏向“都行”“随便”“不强求”，说明你对吃的期待更轻松。'), card('🌈', '升级建议', '随缘很好，但偶尔也可以认真选一顿喜欢的，让校园生活多一点期待。')],
      bars: [bar('不纠结指数', 92, 'blue'), bar('惊喜空间', 70, 'pink'), bar('主动犒赏', 45, 'purple')],
      actions: [action('🍜', '今天主动选一次自己想吃的，不要只说随便。'), action('📍', '收藏一个想试的窗口/店，下次不用纠结。'), action('✨', '给平淡的一餐加一个小惊喜。')],
      share: '我的干饭奶茶人格是佛系饮食派，吃什么都能淡定接住。'
    },
    '电量严重不足': {
      tags: ['红灯电量', '急需休息', '低消耗模式', '先回血'],
      lead: '你的选择显示今天电量已经偏低，结果重点不是激励你硬撑，而是提醒你先休息回血。',
      cards: [card('🪫', '电量状态', '你现在更像红灯提醒：继续硬推只会更累，先停一下反而更有效。'), card('☁️', '选择线索', '你的答案多次出现逃避、困倦、低启动倾向，说明身体和情绪都在要缓冲。'), card('🛟', '回血方案', '今天别追求满血复活，能回 10% 就算赢。')],
      bars: [bar('当前电量', 24, 'pink'), bar('休息需求', 94, 'purple'), bar('执行启动', 32, 'blue')],
      actions: [action('🛋️', '立刻安排一段真正休息，不刷任务不内耗。'), action('🍵', '补水、吃点东西、闭眼 5 分钟，先救急。'), action('✅', '只保留一个最低限度任务，其他先延后。')],
      share: '我今天电量严重不足，先回血比硬撑重要。'
    },
    '半血待机中': {
      tags: ['半血待机', '能撑一点', '小任务回血', '低速启动'],
      lead: '你的选择说明你不是完全没电，但需要用小任务慢慢把状态拉回来。',
      cards: [card('🔋', '电量状态', '你现在是半血待机：能动，但不适合一上来就冲大任务。'), card('⏳', '选择线索', '你的答案在想休息和想完成之间摇摆，说明启动门槛比任务本身更关键。'), card('🧩', '回血方案', '用一个 5 分钟小动作制造完成感，状态会比空等更快回来。')],
      bars: [bar('当前电量', 52, 'blue'), bar('回血速度', 66, 'pink'), bar('大任务承载', 44, 'purple')],
      actions: [action('⏱️', '先做一个 5 分钟内能完成的小任务。'), action('🎧', '配一首熟悉的歌，让启动阻力小一点。'), action('🍬', '完成后给自己一个小奖励，别直接加码。')],
      share: '我今天半血待机中，靠小任务慢慢回血。'
    },
    '电量充足': {
      tags: ['电量充足', '稳定推进', '可持续输出', '奖励机制'],
      lead: '你的选择显示状态已经在可用区间，适合稳定推进，而不是疯狂透支。',
      cards: [card('🔋', '电量状态', '你今天的电量足够处理积压事项，尤其适合推进那些拖了几天的小任务。'), card('📈', '选择线索', '你的答案偏向可执行、能坚持、不过度摆烂，说明当前节奏比较稳。'), card('🎁', '回血方案', '做完一个阶段就奖励一下，稳定输出比一口气爆发更长久。')],
      bars: [bar('当前电量', 78, 'blue'), bar('稳定输出', 84, 'pink'), bar('透支风险', 38, 'purple')],
      actions: [action('📌', '今天适合清掉一个拖延已久的小任务。'), action('✅', '用“完成一项休息一下”的节奏推进。'), action('🎁', '完成后安排一个明确奖励，强化好状态。')],
      share: '我今天电量充足，适合稳定推进待办。'
    },
    '满电出发': {
      tags: ['满电出发', '高效输出', '主动推进', '注意续航'],
      lead: '你的选择明显偏向高能量和高执行，今天适合输出、沟通和推进重点事项。',
      cards: [card('⚡', '电量状态', '你今天像刚充满电，适合处理一直拖着的重点任务。'), card('🚀', '选择线索', '你的答案在多个场景里都偏向主动解决和快速推进，说明执行窗口已经打开。'), card('🧯', '续航提醒', '满电不是无限电，别把所有任务都塞到今天，留一点余量更稳。')],
      bars: [bar('当前电量', 95, 'pink'), bar('执行启动', 90, 'blue'), bar('续航保护', 62, 'purple')],
      actions: [action('🚀', '先处理最重要、最难启动的那件事。'), action('📣', '适合主动沟通，把卡住的问题推进掉。'), action('🧃', '每完成一段就补水休息，别把满电用成透支。')],
      share: '我今天满电出发，适合把重点事项直接推进。'
    },
    '气氛组组长': {
      tags: ['气氛组', '开心果', '热场担当', '快乐扩散'],
      lead: '你的朋友角色是明显的热场型：你在，氛围就不容易冷掉。',
      cards: [card('🎉', '关系位置', '你擅长把朋友从低气压里拉出来，用玩笑、互动和热情让场面变轻松。'), card('💬', '选择线索', '你的选择偏向逗笑、鼓励和主动提议，说明你习惯先把情绪场撑起来。'), card('🫶', '友谊提示', '你也可以偶尔不负责搞笑，把真实情绪交给朋友接住。')],
      bars: [bar('热场能力', 94, 'pink'), bar('快乐扩散', 88, 'purple'), bar('被照顾需求', 58, 'blue')],
      actions: [action('🎈', '今天把一个朋友逗笑，但不必强行营业。'), action('💌', '也说一句自己的真实感受，让朋友靠近你。'), action('🛋️', '给自己留一个安静角落，气氛组也要休息。')],
      share: '我的朋友搭子角色是气氛组组长，有我在就不冷场。'
    },
    '树洞倾听担当': {
      tags: ['树洞倾听', '温柔接住', '不评判', '共情型朋友'],
      lead: '你的朋友角色是高共情倾听者，朋友找你不是因为你话多，而是因为你让人安心。',
      cards: [card('🌳', '关系位置', '你擅长安静听完别人的情绪，不急着评价，这会让朋友觉得被接住。'), card('👂', '选择线索', '你的答案偏向倾听、陪伴、确认感受，说明你在关系里更重视安全感。'), card('💛', '友谊提示', '别只做别人的树洞，你也有被倾听的资格。')],
      bars: [bar('倾听力', 96, 'purple'), bar('共情感', 90, 'pink'), bar('自我表达', 46, 'blue')],
      actions: [action('💬', '今天可以听朋友说，但也给自己设一个情绪边界。'), action('📝', '把自己的烦恼写下来，别全部吞回去。'), action('🤝', '找一个信任的人，说一句“我也想聊聊”。')],
      share: '我的朋友搭子角色是树洞倾听担当，安静但很会接住朋友。'
    },
    '说走就走行动派': {
      tags: ['行动派', '靠谱执行', '说到做到', '带队出发'],
      lead: '你的朋友角色是执行型搭子：遇到问题不只讨论，你会把事情往前推。',
      cards: [card('🏃', '关系位置', '你是朋友里能把“要不要”变成“现在走”的那个人，执行力很有安全感。'), card('🗺️', '选择线索', '你的答案偏向查路线、拉人行动、当面解决，说明你讨厌空转。'), card('🧘', '友谊提示', '行动力很好，但偶尔也允许计划变化，不必每次都冲最前。')],
      bars: [bar('执行力', 95, 'blue'), bar('可靠度', 88, 'pink'), bar('弹性放松', 54, 'purple')],
      actions: [action('📍', '今天适合把一个约定真正落地。'), action('✅', '先做路线/时间这类具体准备，你会很顺手。'), action('🍃', '如果计划变了，也允许自己慢一点。')],
      share: '我的朋友搭子角色是说走就走行动派，靠谱且不拖。'
    },
    '朋友圈军师': {
      tags: ['朋友圈军师', '理性分析', '关键建议', '洞察担当'],
      lead: '你的朋友角色是分析型支持者，朋友来找你，是因为你能把混乱讲清楚。',
      cards: [card('🧠', '关系位置', '你擅长拆问题、看利弊、给方向，关键时刻很容易成为朋友的参谋。'), card('🔍', '选择线索', '你的答案偏向分析、判断和解决方案，说明你习惯先把事情理顺。'), card('💗', '友谊提示', '别把自己只放在“解决问题”的位置，你的感受也同样重要。')],
      bars: [bar('分析力', 95, 'purple'), bar('判断力', 88, 'blue'), bar('情绪表达', 50, 'pink')],
      actions: [action('🧩', '今天可以帮朋友理思路，但别替 TA 做所有决定。'), action('💛', '表达建议前先问一句：你想听建议还是想被陪伴？'), action('🌙', '也给自己的问题留一点思考时间。')],
      share: '我的朋友搭子角色是朋友圈军师，关键时刻能把事理清。'
    }
  }
  return profiles[resultTitle] || null
}

function isGenericResultTitle(title) {
  title = String(title || '').replace(/\s/g, '')
  if (!title) return true
  return title === '测试完成' || title === '完成测试' || title === '已完成' || title === '结果已生成' || title === '你的校园趣测结果已生成' || title === '你的校园隐藏人设已生成' || title === '干饭奶茶人格已生成' || title === '你的校园搭子属性已生成' || title === '你的今日校园状态已生成'
}

function isGenericDescription(desc) {
  desc = String(desc || '')
  return !desc || desc.indexOf('感谢你的参与') >= 0 || desc.indexOf('已完成本次测试') >= 0 || desc.indexOf('这份报告会把你的选择整理') >= 0 || desc.indexOf('你的校园隐藏人设已生成') >= 0
}

function inferDomain(result) {
  var text = [result.category || '', result.testTitle || '', result.resultTitle || ''].join('')
  if (includesAny(text, ['消费', '购物', '预算', '花钱', '下单', '价格', '性价比'])) return 'consume'
  if (includesAny(text, ['干饭', '奶茶', '食堂', '饮食', '零食'])) return 'food'
  if (includesAny(text, ['人格', '性格', '人设'])) return 'persona'
  if (includesAny(text, ['朋友', '社交', '搭子'])) return 'social'
  if (includesAny(text, ['状态', '电量', '回血', '摆烂'])) return 'recharge'
  return 'general'
}

function scoreRatio(result) {
  var score = typeof result.score === 'number' ? result.score : parseInt(result.score || 0, 10) || 0
  var questionCount = result.questionCount || 5
  var maxScore = result.maxScore || questionCount * 4
  if (!maxScore || maxScore < score) maxScore = Math.max(score, 1)
  return clamp(Math.round((score / maxScore) * 100), 0, 100)
}

function domainLabel(domain) {
  var labels = {
    consume: '消费决策',
    persona: '人格倾向',
    food: '干饭补给',
    social: '关系角色',
    recharge: '能量状态',
    general: '综合倾向'
  }
  return labels[domain] || '综合倾向'
}

function normalizeTestTitleForDisplay(result) {
  var domain = inferDomain(result)
  var title = result.testTitle || ''
  if (domain === 'persona' && includesAny(title, ['性格色彩', '校园隐藏人设', '校园人格盲盒'])) return '看看你的班级隐藏角色'
  return title
}

function dominantDimensionFromResult(result) {
  if (result.dominantDimension) return result.dominantDimension
  var counts = result.dimensionCounts || {}
  var keys = Object.keys(counts)
  var best = ''
  var bestCount = 0
  for (var i = 0; i < keys.length; i++) {
    if (counts[keys[i]] > bestCount) {
      best = keys[i]
      bestCount = counts[keys[i]]
    }
  }
  if (best) return best
  var answerSummary = result.answerSummary || []
  for (var j = 0; j < answerSummary.length; j++) {
    var dim = answerSummary[j] && answerSummary[j].dimension
    if (dim) counts[dim] = (counts[dim] || 0) + 1
  }
  keys = Object.keys(counts)
  best = ''
  bestCount = 0
  for (var k = 0; k < keys.length; k++) {
    if (counts[keys[k]] > bestCount) {
      best = keys[k]
      bestCount = counts[keys[k]]
    }
  }
  return best
}

function buildGeneratedProfileFromTitle(title, emoji, dominantTrait) {
  var base = getProfile(title)
  if (!base) return null
  var generated = {}
  for (var key in base) {
    if (Object.prototype.hasOwnProperty.call(base, key)) generated[key] = base[key]
  }
  generated.title = title
  generated.emoji = emoji || '🌟'
  generated.description = (base.cards && base.cards[0] && base.cards[1]) ? (base.cards[0].text + base.cards[1].text) : base.lead
  generated.dominantTrait = dominantTrait || title
  generated.matchPercent = 92
  return generated
}

function buildDimensionGeneratedProfile(result, domain) {
  var dim = dominantDimensionFromResult(result)
  var personaTitles = {
    '显眼包': ['班级显眼包', '🦚', '气氛发动机'],
    '摸鱼王': ['专业摸鱼选手', '🐟', '节能摸鱼'],
    '学霸型': ['低调实力派', '📚', '稳定输出'],
    '透明人': ['隐藏观察者', '👻', '安静观察']
  }
  var foodTitles = {
    '奶茶续命': ['奶茶续命型选手', '🧋', '甜度补给'],
    '干饭第一': ['食堂干饭王', '🍚', '正餐能量'],
    '零食囤积': ['课桌零食库管理员', '🍫', '零食补给'],
    '随缘吃啥': ['佛系饮食派', '🍃', '随缘不纠结']
  }
  var config = domain === 'persona' ? personaTitles[dim] : foodTitles[dim]
  if (!config) return null
  return buildGeneratedProfileFromTitle(config[0], config[1], config[2])
}

function buildScoreGeneratedProfile(result, domain, ratio) {
  var config = null
  if (domain === 'persona') {
    if (ratio <= 30) config = ['隐藏观察者', '👻', '安静观察']
    else if (ratio <= 50) config = ['专业摸鱼选手', '🐟', '节能摸鱼']
    else if (ratio <= 75) config = ['低调实力派', '📚', '稳定输出']
    else config = ['班级显眼包', '🦚', '气氛发动机']
  } else if (domain === 'food') {
    if (ratio <= 30) config = ['佛系饮食派', '🍃', '随缘不纠结']
    else if (ratio <= 50) config = ['课桌零食库管理员', '🍫', '零食补给']
    else if (ratio <= 75) config = ['食堂干饭王', '🍚', '正餐能量']
    else config = ['奶茶续命型选手', '🧋', '甜度补给']
  }
  if (!config) return null
  return buildGeneratedProfileFromTitle(config[0], config[1], config[2])
}

function buildGenericProfile(result) {
  var domain = inferDomain(result)
  var ratio = scoreRatio(result)
  if (domain === 'persona' || domain === 'food') {
    var dimensionProfile = buildDimensionGeneratedProfile(result, domain)
    if (dimensionProfile) return dimensionProfile
    var scoreProfile = buildScoreGeneratedProfile(result, domain, ratio)
    if (scoreProfile) return scoreProfile
  }
  if (domain === 'consume') {
    if (ratio <= 35) {
      return {
        title: '精打细算型消费者',
        emoji: '🧮',
        tags: ['预算优先', '谨慎下单', '重视性价比', '低冲动消费'],
        lead: '你的消费结果不是“测试完成”，而是偏向预算和必要性优先的决策方式。',
        cards: [card('🧮', '你的消费类型', '你买东西前会先看预算、必要性和性价比，不太容易被限时折扣或朋友种草直接带走。'), card('🔍', '为什么是这个结果', '你的选择更偏向先比较、先判断、先确认是否真的需要，所以系统把你归到谨慎规划的一侧。'), card('⚖️', '优势与提醒', '优势是少踩冲动消费的坑；提醒是别把所有喜欢都压成“没必要”，真正高频使用的东西可以适当提高预算。')],
        bars: [bar('预算控制', 92, 'purple'), bar('冲动购买', 24, 'blue'), bar('性价比敏感', 88, 'pink')],
        actions: [action('🧾', '大额消费前保留“是否需要、是否常用、是否超预算”三问。'), action('🛒', '遇到促销先问：没有优惠我还会买吗？'), action('🎁', '给自己留一小部分悦己预算，避免长期压抑。')],
        share: '我的消费风格是精打细算型，预算感和性价比雷达都在线。',
        dominantTrait: '预算控制',
        matchPercent: 82
      }
    }
    if (ratio <= 65) {
      return {
        title: '理性平衡型消费者',
        emoji: '⚖️',
        tags: ['理性消费', '预算感强', '适度悦己', '比较后下单'],
        lead: '你的消费风格处在理性和体验之间：会比较，也愿意为真正喜欢的东西买单。',
        cards: [card('⚖️', '你的消费类型', '你不是纯省钱派，也不是冲动下单派。你通常会先判断需求和预算，再决定要不要为体验感买单。'), card('🧩', '为什么是这个结果', '你的答案显示你会受价格、实用性和心情共同影响，但关键消费前仍会保留比较和判断。'), card('🌿', '优势与提醒', '优势是平衡感不错；提醒是别在“想要”和“应该省”之间反复内耗，提前设好预算会更轻松。')],
        bars: [bar('预算控制', 76, 'purple'), bar('体验追求', 66, 'pink'), bar('冲动购买', 42, 'blue')],
        actions: [action('📌', '给常见消费设一个舒服的预算区间。'), action('🛍️', '想买时先放进清单，隔一晚还想要再下单。'), action('✨', '对高频使用的东西，可以适当为质量和体验付费。')],
        share: '我的消费风格是理性平衡型，会比较，也会适度悦己。',
        dominantTrait: '理性平衡',
        matchPercent: 86
      }
    }
    return {
      title: '体验悦己型消费者',
      emoji: '🛍️',
      tags: ['悦己消费', '体验优先', '容易种草', '即时满足'],
      lead: '你的消费风格更偏体验和情绪价值：喜欢能立刻提升心情、质感或社交体验的选择。',
      cards: [card('🛍️', '你的消费类型', '你更容易被体验感、喜欢程度和即时快乐打动，消费对你来说不只是买东西，也是在给生活加一点质感。'), card('💗', '为什么是这个结果', '你的选择更偏向“喜欢就值得”“先让自己开心”，说明情绪价值和场景体验对你影响较大。'), card('🧯', '优势与提醒', '优势是很会照顾自己的感受；提醒是遇到连续种草时先暂停，避免快乐变成账单压力。')],
      bars: [bar('体验追求', 92, 'pink'), bar('种草敏感', 82, 'purple'), bar('预算控制', 48, 'blue')],
      actions: [action('💳', '给悦己消费单独设置上限，花得开心也花得安心。'), action('⏳', '非刚需商品先等 24 小时，过滤掉短暂冲动。'), action('🧾', '每周回看一次消费记录，找出最值得和最不值得的花费。')],
      share: '我的消费风格是体验悦己型，喜欢为生活质感和快乐买单。',
      dominantTrait: '体验悦己',
      matchPercent: 88
    }
  }
  return null
}

function buildFallbackDesc(result) {
  var title = result.resultTitle || '你的校园趣测结果'
  var testTitle = result.testTitle || '本次测试'
  var questionCount = result.questionCount || 0
  var countText = questionCount ? ('你刚刚完成了 ' + questionCount + ' 道题，') : ''
  return countText + '系统根据你在「' + testTitle + '」里的选择生成了「' + title + '」。这份结果适合当作今天的校园娱乐参考，不代表固定标签，也不需要太认真。'
}

function buildTags(theme, result, profile) {
  if (profile && profile.tags && profile.tags.length) return profile.tags.slice(0, 4)
  var title = result.resultTitle || ''
  var map = {
    consume: ['消费风格', '预算偏好', '决策习惯'],
    daily: ['今日状态', '校园节奏', '轻松参考'],
    persona: ['隐藏人设', '班级角色', '专属气质'],
    food: ['干饭属性', '快乐补给', '校园能量'],
    recharge: ['电量指数', '回血建议', '节奏管理'],
    social: ['朋友角色', '相处风格', '群聊担当'],
    general: ['趣味测试', '状态卡片', '生活参考']
  }
  var tags = (map[theme.key] || map.general).slice()
  if (title && tags.indexOf(title) < 0) tags.unshift(title)
  return tags.slice(0, 4)
}

function buildSummary(result, theme, profile) {
  var desc = result.resultDesc || buildFallbackDesc(result)
  var title = result.resultTitle || '你的校园趣测结果已生成'
  if (profile && profile.lead) {
    return '「' + title + '」' + profile.lead + desc
  }
  var prefixMap = {
    consume: '这份报告会把你的消费选择翻译成具体的决策风格，而不是一句完成提示。',
    daily: '这不是一句简单评价，而是一张属于你今天的校园状态卡。',
    persona: '这个结果把你在校园里的一个高辨识度侧面放大了出来。',
    food: '你的选择透露出一种很有画面感的校园补给方式。',
    recharge: '这份结果更像是今天的能量仪表盘，帮你看见自己的节奏。',
    social: '你在朋友关系里的位置，比一句“外向/内向”更立体。',
    general: '这份报告会把你的选择整理成一张更完整的趣味状态卡。'
  }
  return '「' + title + '」' + (prefixMap[theme.key] || prefixMap.general) + desc
}

function buildSuggestion(result) {
  var text = [result.category || '', result.testTitle || '', result.resultTitle || ''].join('')
  if (includesAny(text, ['干饭', '奶茶', '消费', '食堂'])) return '先给自己补点能量，再处理一个最容易完成的小任务。'
  if (includesAny(text, ['朋友', '同桌', '群聊', '社交', '搭子'])) return '找一个熟悉的人聊两句，轻松一点就好，不用强行营业。'
  if (includesAny(text, ['摆烂', '回血', '拖延', '犯困', '电量'])) return '允许自己慢一点，但别完全关机。先做一个 5 分钟能完成的小动作。'
  if (includesAny(text, ['人设', '显眼包', '班级', '宿舍', '性格'])) return '保留你的校园特色，但不用被任何标签框住，舒服地做自己就行。'
  return '把结果当作一张轻松的状态卡，顺手完成一个小目标，给今天加一点确定感。'
}

function buildInsightCards(result, theme, profile) {
  if (profile && profile.cards && profile.cards.length === 3) return profile.cards
  var title = result.resultTitle || '你的结果'
  var rows = [
    ['🌟', '结果解读', '「' + title + '」来自你刚刚的选择组合，是一张轻松的个人状态卡。'],
    ['🧩', '选择线索', '每一道题都在捕捉你的偏好、节奏和反应方式，组合起来才是完整结果。'],
    ['🪐', '今日提示', '结果不用当成固定定义，把它当作今天的一点灵感就好。']
  ]
  return rows.map(function (row) { return card(row[0], row[1], row[2]) })
}

function clamp(num, min, max) {
  if (num < min) return min
  if (num > max) return max
  return num
}

function buildTraitBars(result, theme, profile) {
  if (profile && profile.bars && profile.bars.length === 3) return profile.bars
  var score = typeof result.score === 'number' ? result.score : parseInt(result.score || 0, 10) || 0
  var questionCount = result.questionCount || 5
  var base = clamp(Math.round((score / Math.max(questionCount * 4, 1)) * 100), 28, 96)
  var configs = {
    consume: ['预算控制', '体验追求', '冲动购买'],
    daily: ['在线感', '松弛度', '行动力'],
    persona: ['辨识度', '稳定感', '反差感'],
    food: ['快乐补给', '分享欲', '续航力'],
    recharge: ['当前电量', '回血速度', '执行启动'],
    social: ['陪伴感', '表达力', '可靠度'],
    general: ['匹配度', '趣味值', '今日感']
  }
  var labels = configs[theme.key] || configs.general
  return [
    bar(labels[0], base, 'pink'),
    bar(labels[1], clamp(100 - Math.floor(base / 3), 40, 92), 'purple'),
    bar(labels[2], clamp(base - 8 + (questionCount * 3), 36, 94), 'blue')
  ]
}

function buildActionList(result, theme, profile) {
  if (profile && profile.actions && profile.actions.length === 3) return profile.actions
  var suggestion = result.resultSuggestion || buildSuggestion(result)
  var actions = {
    consume: [action('🧾', '先把想买的东西分成刚需、改善、冲动三类。'), action('🛒', suggestion), action('⏳', '非刚需消费先等 24 小时再决定。')],
    daily: [action('☀️', '给今天选一个最想完成的小目标。'), action('🍬', suggestion), action('📌', '晚上回看一下：今天哪一刻最像这个结果？')],
    persona: [action('📸', '把这个结果当作今天的人设卡保存下来。'), action('💬', '找同桌/朋友问问：他们觉得像不像？'), action('✨', suggestion)],
    food: [action('🧋', '给自己安排一个不超预算的小补给。'), action('🍚', '认真吃一顿饭，别只靠零食续命。'), action('🌈', suggestion)],
    recharge: [action('⏱️', '先做一个 5 分钟能完成的小任务。'), action('🛋️', '给自己安排一段真正不刷题的休息。'), action('🔋', suggestion)],
    social: [action('💌', '给一个朋友发一句轻松的问候。'), action('👂', '今天聊天时多听一句，也多表达一句。'), action('🤝', suggestion)],
    general: [action('🪐', '把结果当作今天的灵感卡。'), action('🎯', suggestion), action('📮', '分享给朋友看看 TA 的结果会不会一样。')]
  }
  return actions[theme.key] || actions.general
}

function buildReasonList(result, profile) {
  var answerSummary = result.answerSummary || []
  var list = []
  for (var i = 0; i < answerSummary.length && list.length < 3; i++) {
    var item = answerSummary[i] || {}
    if (item.selectedText) list.push('你在「' + (item.question || '这道题') + '」中选择了“' + item.selectedText + '”，这是结果判断的重要线索。')
  }
  if (list.length) return list
  if (profile && profile.cards && profile.cards[1]) return [profile.cards[1].text]
  return ['系统会结合你的题目选择、分数区间和测试主题生成结果，而不是只显示“测试完成”。']
}

function buildStrengthList(result, profile) {
  var text = [result.testTitle || '', result.category || '', result.resultTitle || ''].join('')
  if (includesAny(text, ['消费', '购物', '预算', '消费者'])) {
    return ['能根据需求和预算做取舍', '对价格、体验和实用性有自己的判断', '比单纯跟风更容易买到适合自己的东西']
  }
  if (profile && profile.cards && profile.cards[0]) return [profile.cards[0].text, '这个结果来自你的具体选择组合，不是单纯完成提示。']
  return ['能从选择里看见自己的偏好', '适合把结果当作今天的轻量参考']
}

function buildRiskList(result, profile) {
  var text = [result.testTitle || '', result.category || '', result.resultTitle || ''].join('')
  if (includesAny(text, ['消费', '购物', '预算', '消费者'])) {
    if (includesAny(text, ['悦己', '体验'])) return ['连续被种草时容易超出预算，建议先冷静 24 小时。']
    if (includesAny(text, ['精打细算', '预算'])) return ['过度比较可能让你错过真正提升体验的选择。']
    return ['容易在“想要”和“该省”之间纠结，提前设预算会更轻松。']
  }
  if (profile && profile.cards && profile.cards[2]) return [profile.cards[2].text]
  return ['结果只是娱乐参考，不需要把它当作固定标签。']
}

function normalizeResult(result) {
  var data = result || {}
  var normalized = {}
  for (var key in data) {
    if (Object.prototype.hasOwnProperty.call(data, key)) normalized[key] = data[key]
  }
  normalized.resultTitle = normalized.resultTitle || '你的校园趣测结果已生成'
  normalized.resultEmoji = normalized.resultEmoji || '🌟'
  normalized.testTitle = normalized.testTitle || '校园趣测'
  normalized.score = typeof normalized.score === 'number' ? normalized.score : parseInt(normalized.score || 0, 10) || 0
  normalized.questionCount = normalized.questionCount || 0
  normalized.testTitle = normalizeTestTitleForDisplay(normalized)

  var generatedProfile = null
  if (isGenericResultTitle(normalized.resultTitle) || isGenericDescription(normalized.resultDesc)) {
    generatedProfile = buildGenericProfile(normalized)
    if (generatedProfile) {
      normalized.resultTitle = generatedProfile.title
      normalized.resultEmoji = generatedProfile.emoji || normalized.resultEmoji
      normalized.resultDesc = generatedProfile.description || generatedProfile.lead
      normalized.dominantTrait = generatedProfile.dominantTrait || ''
      normalized.matchPercent = generatedProfile.matchPercent || scoreRatio(normalized)
    }
  }

  normalized.resultDesc = normalized.resultDesc || buildFallbackDesc(normalized)
  normalized.resultSuggestion = normalized.resultSuggestion || buildSuggestion(normalized)
  normalized.matchPercent = typeof normalized.matchPercent === 'number' ? normalized.matchPercent : scoreRatio(normalized)
  normalized.dominantTrait = normalized.dominantTrait || domainLabel(inferDomain(normalized))

  var theme = detectTheme(normalized)
  var profile = generatedProfile || getProfile(normalized.resultTitle)
  normalized.resultTheme = theme
  normalized.resultTags = buildTags(theme, normalized, profile)
  normalized.summaryText = buildSummary(normalized, theme, profile)
  normalized.insightCards = buildInsightCards(normalized, theme, profile)
  normalized.traitBars = buildTraitBars(normalized, theme, profile)
  normalized.actionList = buildActionList(normalized, theme, profile)
  normalized.reasonList = buildReasonList(normalized, profile)
  normalized.strengthList = buildStrengthList(normalized, profile)
  normalized.riskList = buildRiskList(normalized, profile)
  normalized.shareLine = (profile && profile.share) || ('我的结果是「' + normalized.resultTitle + '」，这张测试报告能看到具体倾向。')
  return normalized
}

module.exports = {
  normalizeResult: normalizeResult,
  detectTheme: detectTheme,
  buildFallbackDesc: buildFallbackDesc,
  buildSuggestion: buildSuggestion,
  getProfile: getProfile
}
